### ISSUE TITLE
Function to read images from E57 files

### ISSUE THREAD

**Issue by bigeyesung** [davidcaron/pye57#11]
Hi,
I am trying to add an image-read function in pye57. While I am testing it on my fork branch, I found I could not upload code regarding "libE57Format". That folder belongs to the E57 repo author. Does it mean I need to send a code request to E57 repo first? Or is there any alternatives?

**Comment by davidcaron** [comment]
Hi,

Yes, ideally you would submit your changes there first. My reference to this library must be a bit old, but at first glance images are not supported in libe57format.

The other way would be to "vendorize" libe57format (copy everything in pye57) but if your changes are generic enough, I think your modifications would be welcomed and trying to have them merged there would be beneficial to most.

Either way, I would be happy to accept a PR here.

**Comment by davidcaron** [comment]
Please try version `0.3.1`, I think the case of reading images in pye57 files is covered... It's not a use case I have myself, but according to the recent PRs, it should work.

In particular, see: https://github.com/davidcaron/pye57/pull/13
