### ISSUE TITLE
pye57 installation - xercesc: No such file or directory

### ISSUE THREAD

**Issue by LagiasPaschalis** [davidcaron/pye57#14]
Hi,

**Problem:**
I am working with PyCharm 2019.3.3 professional version, Python 3.8.5 64-bit, Windows 10 and I am trying to install pye57.
I recently installed VS Built Tools 2019 and I have also upgraded my setuptools inside my working virtual environment (not a conda environment).

However, I still get the error below (I have copied and pasted the entire outcome). It seems like file
xercesc/sax2/XMLReaderFactory.hpp
cannot be found.

Any advice would be highly appreciated!

**pye57 installation output message:**

Collecting pye57
  Using cached pye57-0.2.3.tar.gz (159 kB)
Requirement already satisfied: numpy in c:\users\paschalis\documents\2_bedi_consult\venv\lib\site-packages (from pye57) (1.19.2)
Requirement already satisfied: pyquaternion in c:\users\paschalis\documents\2_bedi_consult\venv\lib\site-packages (from pye57) (0.9.9)
Requirement already satisfied: pybind11 in c:\users\paschalis\documents\2_bedi_consult\venv\lib\site-packages (from pye57) (2.6.1)
Using legacy 'setup.py install' for pye57, since package 'wheel' is not installed.
Installing collected packages: pye57
    Running setup.py install for pye57: started
    Running setup.py install for pye57: finished with status 'error'

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Paschalis\Documents\2_bedi_consult\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Paschalis\\AppData\\Local\\Temp\\pycharm-packaging\\pye57\\setup.py'"'"'; __file__='"'"'C:\\Users\\Paschalis\\AppData\\Local\\Temp\\pycharm-packaging\\pye57\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Paschalis\AppData\Local\Temp\pip-record-4bsy69l0\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Paschalis\Documents\2_bedi_consult\venv\include\site\python3.8\pye57'
         cwd: C:\Users\Paschalis\AppData\Local\Temp\pycharm-packaging\pye57\
    Complete output (35 lines):
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pye57
    copying pye57\e57.py -> build\lib.win-amd64-3.8\pye57
    copying pye57\exception.py -> build\lib.win-amd64-3.8\pye57
    copying pye57\scan_header.py -> build\lib.win-amd64-3.8\pye57
    copying pye57\utils.py -> build\lib.win-amd64-3.8\pye57
    copying pye57\__init__.py -> build\lib.win-amd64-3.8\pye57
    copying pye57\__version__.py -> build\lib.win-amd64-3.8\pye57
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building 'pye57.libe57' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\pye57
    creating build\temp.win-amd64-3.8\Release\libE57Format
    creating build\temp.win-amd64-3.8\Release\libE57Format\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IlibE57Format/include -IlibE57Format/src -IlibE57Format/contrib/CRCpp/inc -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\Scripts\Library\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tppye57/libe57_wrapper.cpp /Fobuild\temp.win-amd64-3.8\Release\pye57/libe57_wrapper.obj /EHsc /DVERSION_INFO=\"0.2.3\" /DREVISION_ID=\"pye57-0.2.3\" /DWIN32 /DWINDOWS
    libe57_wrapper.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IlibE57Format/include -IlibE57Format/src -IlibE57Format/contrib/CRCpp/inc -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\Scripts\Library\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /TplibE57Format/src/CheckedFile.cpp /Fobuild\temp.win-amd64-3.8\Release\libE57Format/src/CheckedFile.obj /EHsc /DVERSION_INFO=\"0.2.3\" /DREVISION_ID=\"pye57-0.2.3\" /DWIN32 /DWINDOWS
    CheckedFile.cpp
    libE57Format/src/CheckedFile.cpp(555): warning C4996: 'unlink': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _unlink. See online help for details.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IlibE57Format/include -IlibE57Format/src -IlibE57Format/contrib/CRCpp/inc -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\Scripts\Library\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /TplibE57Format/src/Decoder.cpp /Fobuild\temp.win-amd64-3.8\Release\libE57Format/src/Decoder.obj /EHsc /DVERSION_INFO=\"0.2.3\" /DREVISION_ID=\"pye57-0.2.3\" /DWIN32 /DWINDOWS
    Decoder.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IlibE57Format/include -IlibE57Format/src -IlibE57Format/contrib/CRCpp/inc -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\Scripts\Library\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /TplibE57Format/src/E57Foundation.cpp /Fobuild\temp.win-amd64-3.8\Release\libE57Format/src/E57Foundation.obj /EHsc /DVERSION_INFO=\"0.2.3\" /DREVISION_ID=\"pye57-0.2.3\" /DWIN32 /DWINDOWS
    E57Foundation.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IlibE57Format/include -IlibE57Format/src -IlibE57Format/contrib/CRCpp/inc -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\Scripts\Library\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\lib\site-packages\pybind11\include -IC:\Users\Paschalis\Documents\2_bedi_consult\venv\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include -IC:\Users\Paschalis\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /TplibE57Format/src/E57FoundationImpl.cpp /Fobuild\temp.win-amd64-3.8\Release\libE57Format/src/E57FoundationImpl.obj /EHsc /DVERSION_INFO=\"0.2.3\" /DREVISION_ID=\"pye57-0.2.3\" /DWIN32 /DWINDOWS
    E57FoundationImpl.cpp
    libE57Format/src/E57FoundationImpl.cpp(32): fatal error C1083: Cannot open include file: 'xercesc/sax2/XMLReaderFactory.hpp': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Paschalis\Documents\2_bedi_consult\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Paschalis\\AppData\\Local\\Temp\\pycharm-packaging\\pye57\\setup.py'"'"'; __file__='"'"'C:\\Users\\Paschalis\\AppData\\Local\\Temp\\pycharm-packaging\\pye57\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Paschalis\AppData\Local\Temp\pip-record-4bsy69l0\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Paschalis\Documents\2_bedi_consult\venv\include\site\python3.8\pye57' Check the logs for full command output.

**Comment by Shinyshadow** [comment]
I have exactly the same problem. Could you fix it somehow?

**Comment by Christian3point14** [comment]
For anyone having this issue on a linux machine: for me the solution was https://stackoverflow.com/a/19253719
copied from there:
    You can create .pydistutils.cfg file in your home directory and override build options like you could do with custom setup.cfg, but without need to unpack package first.
    
    So, for example, you can write something like this to alter include & lib search path:
    `[build_ext]
    include_dirs=/usr/local/include
    library_dirs=/usr/local/lib64
    rpath=/usr/local/lib64`

And here is a good explanation on how and why that works: https://bouktin.blogspot.com/2012/04/configure-pydistutilscfg-python.html

**Comment by LagiasPaschalis** [comment]
@Christian3point14 thank you very much for your reply, I haven't tried to further to solve this issue after posting it here.
I will go through your suggestion and the material covered in the links you sent.
I am working in a Windows 10 environment, hopefully the solution will be the same!

**Comment by davidcaron** [comment]
Hi, sorry for the delay, please try to install the newest version on pypi. They bundle a dll of xerces-c, so hopefully a simple `pip install -U pye57` will fix the issue.

**Comment by LagiasPaschalis** [comment]
@davidcaron Thank you for your answer. I tried it and it worked - I now have pye57 installed in my virtual environment! I am closing the issue, thanks again to everyone who replied!

**Comment by RyanRConaway** [comment]
It appears this issue is relevant again after 0.4.1, at least on MacOS.

0.4.2 removed `include_package_data=True` inside setup.py, which actually fixes an issue with absolute paths being included during a pyproject.toml wheel build, however, xerces-c has to be externally installed.

I notice this library doesn't mention MacOS. Is MacOS "supported" at all? It would be wonderful to include xerces-c for a MacOS build so the library could be installed standalone.

**Comment by dancergraham** [comment]
Yes macos support would be great - do you know whether xerces c can be installed in the same way as for Linux?
