### ISSUE TITLE
Read and Write BlobNodes (Image2D)

### ISSUE THREAD

**Issue by tiagomfmadeira** [davidcaron/pye57#15]
Greetings,

I have implemented wrapper functions for reading and writing BlobNodes in my fork of this repo.

I have also added a [simple example](https://github.com/tiagomfmadeira/pye57/blob/master/examples/pye57_camera_example.py) showing how to extract and display 2D images (the "jpegImage" Blob objects which are part of the pinholeRepresentation of image2D objects).

Would this be of interest to integrate through a PR?

Thank you for your time

**Comment by davidcaron** [comment]
Hi, 

I think this was implemented in a very similar way in https://github.com/davidcaron/pye57/pull/13.

This was just merged and released, could you try your example script with the newest version?

If something is still missing, feel free to submit a PR, wee can look at it then.

Thanks
