### ISSUE TITLE
Export spherical image from e57file which not contains 2D Image

### ISSUE THREAD

**Issue by pierrenavarra** [davidcaron/pye57#39]
Hi,
I've got a cool code to extract image2D from an e57 file wich contains a 2D Image.
I use this : 
`e57 = pye57.E57(e57filename)

imageFile = e57.image_file
root = imageFile.root()`

My question is how to extract jpg spherical image when NO image is on the e57 file?
I suppose I have to convert all of my points for spherical but how???
Should I use pcl package or anything?
Thx!

**Comment by pierrenavarra** [comment]
Any idea?

**Comment by dancergraham** [comment]
Hello, I think this is outside the scope of this library - it is post-processing work and is not related to e57 file reading and writing
