### ISSUE TITLE
extract image

### ISSUE THREAD

**Issue by arthur-leguennec** [davidcaron/pye57#4]
Hello everyone,

I would like to know if it is possible to extract the images present in the file e57 ?
I tried this:
`imf = e57.image_file`
`root = imf.root()`

By I don't have the key "data3d" inside

**Comment by davidcaron** [comment]
Unfortunately no, images are not supported yet. PRs are welcome.

data3d should be available though...

**Comment by Khsaadi** [comment]
Hi,
I have a similar problem. I am trying to read the jpeg image saved in the e57 file. Are there any updates? are images currently supported?
Thanks in advance.

**Comment by AlbionS** [comment]
Hi,

I am interested for this feature too. Is it possible to extract images or build images  like the e57unpack.exe ?

@davidcaron

**Comment by davidcaron** [comment]
Hi, could you try the latest version (0.3.1)?

I believe this should work now. See these PRs in particular: https://github.com/davidcaron/pye57/pull/13 https://github.com/davidcaron/pye57/pull/12
