### ISSUE TITLE
How can I insert my panoramic images in the correct position (in a 3D view) after extracting them from an E57 file?

### ISSUE THREAD

**Issue by Musaub7** [davidcaron/pye57#41]
I have been having trouble finding answers for this. I have extracted images after reading the E57 file. How am I supposed to get the cartesian coordinates for the image (for every pixel perhaps) or project them onto the point cloud? I have spherical representation for the images and the 3D point cloud data is in cartesian coordinates. What information do I need and how am I supposed to use it?

**Comment by dancergraham** [comment]
Hello I think this is outside the scope of this library - the library only aims to let you read the ponts and the images, not to carry out projections and transformations on the contained data. Another library such as Open3D may help with this.
