### ISSUE TITLE
can not install in python 3.11

### ISSUE THREAD

**Issue by mcmingchang** [davidcaron/pye57#48]
can not install in python 3.11

**Comment by dancergraham** [comment]
Hello, 
Cloning the repo and following the steps described in this issue might help 
https://github.com/davidcaron/pye57/issues/38

**Comment by mcmingchang** [comment]
adding license file 'LICENSE'
      writing manifest file 'src\pye57.egg-info\SOURCES.txt'
      error: Error: setup script specifies an absolute path:

          C:\Users\klarity\Downloads\pye57\libE57Format\src\BlobNodeImpl.cpp

      setup() arguments must *always* be /-separated paths relative to the
      setup.py directory, *never* absolute paths.

**Comment by mcmingchang** [comment]
I was facing the same error and fixed it by commenting out
include_package_data=True
in module  setup.py

**Comment by itsb** [comment]
I ended up keeping include_package_data=True but changed setup.py to use relative paths as the errors suggested. I also updated setup.py to use the xerces dll from the conda environment, so I did not need to build that from source. I built a wheel for python 3.11 from my conda env that I use in my conventional pip venv. I published the wheel at: https://github.com/itsb/pye57/releases/tag/pye57-py311
