### ISSUE TITLE
Segmentation fault error un Ubuntu 18.04

### ISSUE THREAD

**Issue by clausmichele** [davidcaron/pye57#5]
Successfully installed with pip3 after building xerces.
Now if I try simply to import pye57 I get an error:
```
import pye57
Segmentation fault (core dumped)
```

**Comment by davidcaron** [comment]
Hi, sorry for the delay, please try to install the newest version on pypi. There are manylinux wheels, so hopefully `pip install -U pye57` will fix the issue.

As per your particular question on why you get a segmentation fault, it's difficult to find the problem without more information on your environment.

Feel free to reopen if you have issues with the newest version.
