### ISSUE TITLE
publish 3.12 wheels to pypi

### ISSUE THREAD

**Issue by itsb** [davidcaron/pye57#52]
Thanks for the 0.4.2 update with 3.11 and 3.12 support. Somehow the github workflow failed to publish wheels for 3.11 and 3.12 to pypi.

**Comment by dancergraham** [comment]
Hello thanks yes it was an issue with a pinned version of cibuildwheel! I have pushed again and it now builds up to 3.11 wheels for Windows and up to 3.12 wheels for Linux. I am still looking into how to get version 3.12 wheels for Windows

**Comment by dancergraham** [comment]
Thanks to @amangupta17 recent updates this seems to be fixed for python 3.12 as well !
