### ISSUE TITLE
setup.py stops

### ISSUE THREAD

**Issue by ShunnosukeKataoka** [davidcaron/pye57#7]
In Ubuntu 18.04.2 LTS on AWS, when I run `pip install pye57` , there is a problem that I can not proceed from setup.py. It runs in the environment of Python 3.7 built on Anaconda.

```
~$ pip install pye57
Collecting pye57
  Using cached https://files.pythonhosted.org/packages/66/37/bc000ec2bc87afcd7b90a2b9ff772aafcfcfb2d91d11e74fd64439e2c3aa/pye57-0.2.3.tar.gz
Requirement already satisfied: numpy in ./anaconda3/envs/kajima/lib/python3.7/site-packages (from pye57) (1.16.4)
Requirement already satisfied: pyquaternion in ./anaconda3/envs/kajima/lib/python3.7/site-packages (from pye57) (0.9.5)
Requirement already satisfied: pybind11 in ./anaconda3/envs/kajima/lib/python3.7/site-packages (from pye57) (2.2.4)
Building wheels for collected packages: pye57
  Building wheel for pye57 (setup.py) ... 
```

**Comment by AlbionS** [comment]
I have the same issue.
@ShunnosukeKataoka  were you able to install pye57 in Ubuntu 18 on AWS ?

**Comment by bigeyesung** [comment]
Hi @ShunnosukeKataoka,
just came across your post.
did you find the solution?
maybe try a different version first?
or try to install from Github: 
```
git clone project
pip install -e .
```

**Comment by davidcaron** [comment]
Hi, sorry for the delay, please try to install the newest version on pypi. There are manylinux wheels, so hopefully `pip install -U pye57` will fix the issue.
