### ISSUE TITLE
Partial read of E57 file

### ISSUE THREAD

**Issue by Ephraim-Bryski** [davidcaron/pye57#74]
I'm trying to read very large (millions of points) e57 files with pye57. However, I'm only interested in a small fraction of the points, and I know the indices of these points (e.g. points 3000 to 3100). It looks like both `read_scan` and `read_scan_raw` read all the point data from one scan at a time. This is prohibitively expensive for these large files (a few minutes in, the script just crashes). In theory, I imagine it would be possible to determine where in the file the points of interest are and only read that portion. Is this currently possible in pye57? If not, is there interest in implementing it, or is there some workaround for this?

**Comment by dancergraham** [comment]
Hello I don't know a way to do this but I think it is supported by the underlying c++ library so in theory it may be already possible, or possible to add...

**Comment by Ephraim-Bryski** [comment]
That's good to know it's likely in libe57; it would be great if that functionality were exposed or reimplemented in pye57.

If I were to seek() and read() into the file directly, I'm guessing I wouldn't be relying on pye57 (or at least not as much). I have thought about just parsing the e57 myself instead as the format doesn't seem too complicated (it looks like the approach is read the header, locate and read the xml, from the xml get the location and layout of the point data, and finally read the data, being careful to skip the checksums). I'm guessing there could be a lot more complications if I do it myself, but maybe that's the easiest approach for my case.

**Comment by dancergraham** [comment]
It is exposed as `pye57.libe57.CompressedVectorReader` including the seek and read methods but I haven't tried it - I would be very interested if you can get it to work and it would be useful for #45

**Comment by dancergraham** [comment]
Ahh this issue suggests that seek may not actually be implemented: https://github.com/asmaloney/libE57Format/issues/244

**Comment by dancergraham** [comment]
alternatively this may be easier to add to the `e57` python library which wraps the rust library of the same name.  The rust library seems to include this option.  You can also use the rust library to extract csv files from e57 files and then just select the points you want from there. It is a bit wasteful as you are writing a huge text file and then throwing most of it away but it may solve your problem

**Comment by dancergraham** [comment]
For now I will close this issue as it is impossible given the current scope and capabilities of libe57format
