### ISSUE TITLE
Error extracting data

### ISSUE THREAD

**Issue by sebaFP** [davidcaron/pye57#8]
Hello,
I am extracting data from differents E57 that has its center about x=100, y=100, z=2000, but when i print the new data at axis z changes to about -2 to 2.
How can I fix it? Can I extract the data as string?
link of an example file: [https://gofile.io/d/auwmD3](url)

Thanks!

**Comment by davidcaron** [comment]
Hi, sorry for the delay. I'm not sure I understand the problem exactly, looking at the file would help, but unfortunately the link to the file doesn't work anymore.
